Repository codeit-fe2-2/taskify, pull requests merged in 2024-01, with the labels that each got.

#6 test
  README.md
Labels: :book: Documentation

#7 Feat: 프로젝트 기초 세팅
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/dashboard/[boardid]/edit.tsx
  pages/dashboard/[boardid]/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  postcss.config.js
  pull_request_template.md
  src/components/ui/Button.tsx
  static/fonts/Pretendard-Bold.subset.woff2
  static/fonts/Pretendard-Medium.subset.woff2
  static/fonts/Pretendard-Regular.subset.woff2
  static/fonts/Pretendard-SemiBold.subset.woff2
  styles/fonts.ts
  styles/globals.css
  tailwind.config.ts
Labels: :gear: Setting

#16 feat: test 페이지, 공통 컴포넌트 추가
  pages/test/index.tsx
  src/components/auth/LoginForm.tsx
  src/components/dashboard/Column.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideMenu.tsx
  src/components/ui/Card.tsx
  src/components/ui/Input.tsx
  src/components/ui/Modal.tsx
Labels: :bulb: Feature

#22 Feat : Modal/Input 컴포넌트 일부 구현 (3.5/7)
  package-lock.json
  pages/test/index.tsx
  public/icons/check.svg
  src/components/ui/ModalInput.tsx
Labels: :bulb: Feature

#26 Feat: 사이드 메뉴 바 개발 외
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  public/favicon.ico
  public/icons/logo.svg
  public/icons/logo_taskify.svg
  public/icons/taskify.svg
  public/next.svg
  public/vercel.svg
  src/apis/axiosInstance.ts
  src/components/layout/CommonLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideMenu.tsx
  src/types/dashboard.ts
  styles/globals.css
  tsconfig.json
Labels: :bulb: Feature

#25 Feat : Modal/Input 컴포넌트 구현 (3.5+3.5/7)
  .gitignore
  package-lock.json
  package.json
  pages/_document.tsx
  pages/test/index.tsx
  public/icons/edit.svg
  public/images/modalImageInputImage.png
  src/components/ui/ModalInput.tsx
  src/util/formatDateTime.tsx
  styles/globals.css
  styles/react-datetime.css
Labels: :bulb: Feature, :gear: Setting

#24 Feat: Input 컴포넌트 구현
  src/components/ui/Input.tsx
Labels: :bulb: Feature

#30 Feat: 공통 버튼 컴포넌트 텍스트 부분 작업
  .gitignore
  pages/test/index.tsx
  public/icons/arrowBefore.svg
  public/icons/arrowBeforeDisabled.svg
  public/icons/arrowNext.svg
  public/icons/arrowNextDisabled.svg
  public/icons/plus.svg
  src/components/ui/Button/GeneralButton.tsx
  src/components/ui/Button/IconButton.tsx
  tailwind.config.ts
Labels: :bulb: Feature, :art: Style

#32 Refactor: Modal/Input 컴포넌트 리팩토링
  package-lock.json
  package.json
  pages/test/index.tsx
  pages/test/mockup.json
  src/components/ui/ModalInput.tsx
  src/components/ui/ModalInput/ModalDropdown.tsx
  src/components/ui/ModalInput/ModalImage.tsx
  src/components/ui/ModalInput/ModalInput.tsx
  src/components/ui/ModalInput/ModalTextarea.tsx
  src/components/ui/ModalInput/inputClassNames.ts
  tailwind.config.ts
Labels: :hammer_and_wrench: Refactor

#37 Feature: 헤더 컴포넌트 외
  pages/dashboard/[boardid]/edit.tsx
  pages/dashboard/[boardid]/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  src/apis/axiosInstance.ts
  src/components/layout/BasicLayout.tsx
  src/components/layout/CommonLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideMenu.tsx
  src/constants/routes.ts
  src/hooks/dashboard/useGetColumnList.ts
  src/hooks/dashboard/useGetDashboard.ts
  src/hooks/dashboard/useGetDashboardList.ts
  src/hooks/useAsync.ts
  src/types/dashboard.ts
  src/types/user.ts
Labels: :bulb: Feature
