Repository codeit-fe2-2/taskify, pull requests merged in 2024-02, with the labels that each got.

#39 Feature/eunji/10
  pages/test/index.tsx
  public/icons/chip_add.svg
  public/icons/chip_check.svg
  public/icons/chip_ellipse_sm_purple.svg
  src/components/ui/AddButton.tsx
  src/components/ui/Card.tsx
  src/components/ui/Chips/Chips.tsx
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/Chips/CountNumberChip.tsx
  src/components/ui/Chips/DotNameTagChip.tsx
  src/components/ui/ColorDotButton.tsx
  tailwind.config.ts
Labels: :hammer_and_wrench: Refactor

#43 Feature/00TaciTa00/11 : Modal/Input 컴포넌트 작성
  pages/test/index.tsx
  pages/test/mockup.json
  src/components/ui/ModalInput/ModalDropdown.tsx
  src/components/ui/ModalInput/ModalImage.tsx
  src/components/ui/ModalInput/ModalInput.tsx
  src/components/ui/ModalInput/ModalTextarea.tsx
  src/components/ui/ModalInput/inputClassNames.ts
Labels: :bulb: Feature, :hammer_and_wrench: Refactor

#44 Feat: 랜딩페이지 구현
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/landing/Header.tsx
  pages/test/index.tsx
  public/icons/logoDark.svg
  public/icons/taskifyDark.svg
  src/components/landing/Footer.tsx
  src/components/landing/LandingHeader.tsx
  src/components/landing/LandingMain.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/components/ui/Button/DarkModeButton.tsx
  src/components/ui/Button/TextButton.tsx
  tailwind.config.ts
Labels: :bulb: Feature, :art: Style, :gear: Setting

#52 Feature/00TaciTa00/45 : Table 컴포넌트 임시 작성
  pages/test/index.tsx
  pages/test/invitedash.json
  pages/test/mockup.json
  src/components/ui/Table/InvitedashTable.tsx
  src/components/ui/Table/InvitelistTable.tsx
  src/components/ui/Table/MemberTable.tsx
  src/components/ui/Table/TableLayer.tsx
Labels: :bulb: Feature

#51 Feature: Alert모달 구현 (delete, passwordError)
  pages/index.tsx
  pages/test/index.tsx
  src/components/ui/Button/DashBoardButton.tsx
  src/components/ui/Modal/AlertModal.tsx
Labels: :bulb: Feature, :art: Style, :hammer_and_wrench: Refactor

#57 feat: 나의 대시보드 페이지 구현
  pages/index.tsx
  pages/mydashboard/index.tsx
  src/components/layout/BasicLayout.tsx
  src/components/layout/Header.tsx
  src/components/ui/Input.tsx
  src/hooks/dashboard/useGetDashboardList.ts
  styles/globals.css
Labels: :bulb: Feature

#53 Feature/00TaciTa00/45 : Table 컴포넌트 작성
  pages/test/index.tsx
  pages/test/invitedash.json
  pages/test/mockup.json
  src/components/ui/Table/InvitedashTable.tsx
  src/components/ui/Table/InvitelistTable.tsx
  src/components/ui/Table/MemberTable.tsx
  src/components/ui/Table/TableLayer.tsx
  src/hooks/table/useDeleteInviteList.ts
  src/hooks/table/useDeleteMembers.ts
  src/hooks/table/useGetInviteList.ts
  src/hooks/table/useGetInvitedash.ts
  src/hooks/table/useGetMembers.ts
  src/hooks/table/usePutInviteDash.ts
  src/types/table.ts
Labels: :bulb: Feature

#61 Refactor: Input width 스타일, 기본 브라우저 메시지 제거 등 수정
  src/components/ui/Input.tsx
Labels: :hammer_and_wrench: Refactor

#62 Chips 중 ColorDotChip 수정
  pages/test/index.tsx
  src/components/ui/AddButton.tsx
  src/components/ui/Card.tsx
  src/components/ui/Chips/Chips.tsx
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/Chips/DotNameTagChip.tsx
  src/components/ui/ColorDotButton.tsx
Labels: :bulb: Feature

#60 Feature: 모달 시스템 및 공통 모달 구현
  pages/_app.tsx
  src/components/ui/Modal.tsx
  src/components/ui/Modal/ConfirmModal.tsx
  src/components/ui/Modal/ContextModal.tsx
  src/components/ui/ModalWrapper.tsx
  src/contexts/ModalProvider.tsx
Labels: :bulb: Feature

#67 refactor: 컴포넌트 분리 및 반응형 레이아웃 추가
  pages/mydashboard/index.tsx
  src/components/mydashboard/MyDashboardList.tsx
  src/components/mydashboard/NoInvitedDashboard.tsx
Labels: :art: Style, :hammer_and_wrench: Refactor

#64 AddButton, DotNameTagChip, CountNumberChip 기능구현
  pages/test/index.tsx
  src/components/ui/AddButton.tsx
  src/components/ui/Chips/Chips.tsx
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/Chips/CountNumberChip.tsx
  src/components/ui/Chips/DotNameTagChip.tsx
  src/components/ui/ColorDotButtons.tsx
Labels: :bulb: Feature, :hammer_and_wrench: Refactor

#72 Feat: AlertModa CreateModal 구현
  menualButton.txt
  pages/test/index.tsx
  src/components/ui/Button/DarkModeButton.tsx
  src/components/ui/Button/IconButton.tsx
  src/components/ui/Button/TextButton.tsx
  src/components/ui/ColorDotButtons.tsx
  src/components/ui/Modal/AlertModal.tsx
  src/components/ui/Modal/CreateModal.tsx
Labels: :bulb: Feature, :art: Style, :hammer_and_wrench: Refactor

#65 Feat : Table 컴포넌트에 useRouter, 미디어 쿼리, 페이지네이션 적용
  next.config.mjs
  pages/dashboard/[boardid]/edit.tsx
  pages/test/index.tsx
  public/icons/add_box_white.svg
  src/components/ui/Table/InvitedashTable.tsx
  src/components/ui/Table/InvitelistTable.tsx
  src/components/ui/Table/MemberTable.tsx
  src/components/ui/Table/TableLayer.tsx
  src/hooks/table/useDeleteInviteList.ts
  src/hooks/table/useDeleteMembers.ts
  src/hooks/table/useGetInviteList.ts
  src/hooks/table/useGetInvitedash.ts
  src/hooks/table/useGetMembers.ts
  src/hooks/table/usePutInviteDash.ts
  src/hooks/useAsync.ts
Labels: :bug: Bug Fix, :bulb: Feature, :hammer_and_wrench: Refactor

#69 Feat: 로그인 페이지 초기 구현
  pages/_app.tsx
  pages/login/index.tsx
  public/icons/logo_large.svg
  src/contexts/AuthProvider.tsx
  src/hooks/useAuth/usePostLogin.ts
  src/types/auth.ts
Labels: :bulb: Feature

#78 feat : ProfileImage 없는 member의 경우 임시로 쓰기 좋은 DefaultProfileImage.tsx 작성
  pages/test/index.tsx
  src/components/ui/DefaultProfileImage.tsx
Labels: :bulb: Feature

#79 Fix : MemberTable의 멤버에 ProfileImageUrl이 없으면 에러가 생기는 현상 수정
  src/components/ui/Table/MemberTable.tsx
Labels: :bug: Bug Fix

#84 Refactor : ModalDropdown에 신규 컴포넌트 적용
  pages/dashboard/[boardid]/index.tsx
  pages/test/DropdownMockup.json
  pages/test/index.tsx
  src/components/ui/Chips/DotNameTagChip.tsx
  src/components/ui/ModalInput/ModalDropdown.tsx
Labels: :hammer_and_wrench: Refactor

#85 feat: 헤더 컴포넌트 완성
  package-lock.json
  package.json
  src/components/layout/BasicLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideMenu.tsx
  src/components/ui/DefaultProfileImage.tsx
  src/hooks/useAuth/useGetMe.ts
Labels: :bulb: Feature

#87 feat: mydashboard 페이지 합침
  pages/mydashboard/index.tsx
  src/components/mydashboard/MyDashboardList.tsx
  src/components/ui/Table/InvitedDashboardTable.tsx
Labels: :bulb: Feature

#88 Feat : ModalInput 태그에 ColorTagChip 적용
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/ModalInput/ModalInput.tsx
  src/components/ui/ModalInput/inputClassNames.ts
Labels: :bulb: Feature

#91 Feat: 회원가입 페이지 구현 외 로그인 리팩터링, useAxios 훅
  pages/login/index.tsx
  pages/signup/index.tsx
  src/components/ui/Input.tsx
  src/constants/routes.ts
  src/hooks/useAuth/useAxios.ts
  src/hooks/useAuth/usePostLogin.ts
  src/hooks/useAuth/usePostSignup.ts
  src/types/auth.ts
Labels: :bulb: Feature, :hammer_and_wrench: Refactor

#92 feature: Header 컴포넌트 초대하기 버튼에 모달 및 기능 구현
  src/components/layout/BasicLayout.tsx
  src/components/layout/SideMenu.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/InvitationButton.tsx
  src/components/ui/Icon.tsx
  src/components/ui/Modal/ConfirmModal.tsx
  src/constants/icons.ts
  src/hooks/dashboard/useInviteMember.ts
  src/types/dashboard.ts
  styles/globals.css
Labels: :bulb: Feature

#98 feat: 대시보드 추가하기 기능 구현
  pages/dashboard/[boardid]/index.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  public/icons/setting.svg
  src/apis/card/getCardList.ts
  src/apis/dashboard/deleteColumn.ts
  src/apis/dashboard/getColumnList.ts
  src/apis/dashboard/getDashboardList.ts
  src/apis/dashboard/postCreateColumn.ts
  src/apis/dashboard/postCreateDashboard.ts
  src/apis/dashboard/putColumnName.ts
  src/apis/myPage/getMe.ts
  src/apis/myPage/postProfileImageURL.ts
  src/apis/myPage/putChangedPassword.ts
  src/apis/myPage/putChangedUserInfo.ts
  src/components/dashboard/Card.tsx
  src/components/dashboard/CardList.tsx
  src/components/landing/Footer.tsx
  src/components/landing/LandingHeader.tsx
  src/components/landing/LandingMain.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/components/layout/BasicLayout.tsx
  src/components/layout/SideMenu.tsx
  src/components/mypage/AddImage.tsx
  src/components/mypage/PasswordChange.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/ui/Card.tsx
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/Modal/AlertModal.tsx
  src/components/ui/Modal/CardDetails.tsx
  src/components/ui/Modal/CreateModal.tsx
  src/hooks/dashboard/usecolumnistget.ts
  src/hooks/useAsync.ts
Labels: :bulb: Feature, :art: Style, :hammer_and_wrench: Refactor

#94 Docs : README.md 1차 수정
  README.md
  package.json
Labels: :book: Documentation

#99 TodoModal 작성 중 (미완성)
  pages/dashboard/[boardid]/edit.tsx
  pages/dashboard/[boardid]/index.tsx
  pages/test/index.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/CardList.tsx
  src/components/ui/AddButton.tsx
  src/components/ui/ColorDotButton.tsx
  src/components/ui/Modal/CardDetails.tsx
  src/components/ui/Modal/TodoModal.tsx
  src/components/ui/ModalInput/ModalDropdown.tsx
  src/components/ui/ModalInput/ModalImage.tsx
Labels: :bulb: Feature

#100 Feat : CardDetail 모달 임시 저장
  pages/test/index.tsx
  public/icons/more_vert.svg
  src/apis/card/useGetCardDetail.ts
  src/apis/card/useGetComments.ts
  src/components/ui/Modal/CardDetails.tsx
  src/components/ui/ModalInput/ModalTextarea.tsx
  src/components/ui/ModalInput/inputClassNames.ts
  src/hooks/Card/useGetCardDetail.ts
  src/hooks/Card/useGetCommentList.ts
  src/types/card.ts
Labels: :bulb: Feature

#104 Fix: 빌드 가능하도록 타입 에러 등 수정
  pages/index.tsx
  pages/test/DropdownMockup.json
  pages/test/[boardid]/index.tsx
  pages/test/index.tsx
  src/apis/card/useGetCommentList.ts
  src/apis/card/useGetComments.ts
  src/apis/card/usePostComment.ts
  src/apis/myPage/putChangedUserInfo.ts
  src/components/dashboard/CardList.tsx
  src/components/landing/LandingMain.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/InvitationButton.tsx
  src/components/mypage/PasswordChange.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/ui/Button/TextButton.tsx
  src/components/ui/Chips/ColorTagChip.tsx
  src/components/ui/Modal/CardDetails.tsx
  src/components/ui/Modal/TodoModal.tsx
  src/components/ui/ModalInput/ModalDropdown.tsx
  src/components/ui/ModalInput/ModalImage.tsx
  src/components/ui/ModalInput/ModalTextarea.tsx
  src/components/ui/Table/InvitelistTable.tsx
  src/hooks/Card/useGetCardDetail.ts
  src/hooks/table/useDeleteInviteList.ts
  src/hooks/table/useDeleteMembers.ts
  src/hooks/table/usePutInviteDash.ts
  src/hooks/useAuth/usePostLogin.ts
  src/hooks/useAuth/usePostSignup.ts
  src/types/card.ts
Labels: :bug: Bug Fix

#106 Refactor: mypage새로운 대시보드 생성 이벤트처리리
  pages/index.tsx
  src/components/dashboard/CardList.tsx
  src/components/layout/SideMenu.tsx
  src/components/mydashboard/MyDashboardList.tsx
Labels: :hammer_and_wrench: Refactor

#107 Docs : 찬주님 작성해주세요...(초롱초롱)
  README.md
Labels: :book: Documentation

#110 document: 리드미 추가
  README.md
Labels: :book: Documentation

#118 fix : scrollbar hide, getMe 수정
  pages/dashboard/[boardid]/index.tsx
  pages/index.tsx
Labels: :bug: Bug Fix

#119 feature: 헤더 프로필 사진 나오게 구현
  src/components/layout/header/Header.tsx
Labels: :bulb: Feature
